-- Phase 3: Bring-Your-Own-Key (BYOK)
-- Run once in Supabase SQL Editor (Dashboard → SQL Editor → New query → Run)

create table if not exists public.user_api_keys (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  provider text not null,
  api_key text not null,
  base_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

-- Backend-only access (same style as other bot tables)
alter table public.user_api_keys enable row level security;
-- No public policies on purpose: only service/anon key used by the bot backend.

create index if not exists user_api_keys_user_id_idx
  on public.user_api_keys (user_id);

comment on table public.user_api_keys is
  'Per-user inference API keys (BYOK). provider: dahl|openrouter|groq|cerebras|siliconflow|mistral|github|custom';
