-- Phase 7: saved prompts + bot mode
-- Run AFTER 04_storage_lifetime.sql

create table if not exists public.user_prompts (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  name text not null,
  prompt text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.user_prompts disable row level security;

create index if not exists user_prompts_user_id_idx
  on public.user_prompts (user_id);

alter table public.users
  add column if not exists bot_mode text;

comment on table public.user_prompts is
  'Named user prompts for Manus (Telegram caption length limit workaround)';
comment on column public.users.bot_mode is
  'chat | manus — exclusive bot mode; null = chat default';
